      <footer>
        <img src="footerlogo.png" alt="Footer Logo" style="height: 150px;">   
        <p>&copy; 2025 Cyber Nova Inc.</p>
        <p>Jira Board: <a href="https://student-team-p6pajg6n.atlassian.net/jira/software/projects/WTP/summary" target="_blank">Click here</a></p>
        <p>GitHub: <a href="https://github.com/Shriyans007/Web-Tech-Project.git" target="_blank">Click here</a></p>
        <p><a href="mailto:info@cybernova.com.au">Contact CyberNova</a></p>


    </footer>